const constants = {
  DATE_TIME_FORMAT: "YYYY-MM-DD HH:mm:ss",
  VIEW: "view",
  CREATE: "create",
  UPDATE: "update",
  limit: 10,
  TURN_ON_AUTO_UPDATE: "TURN_ON_AUTO_UPDATE",
  RESTART_VPS: "RESTART_VPS",
  UPDATE_PLUGIN_AND_WORDPRESS_CORE: "UPDATE_PLUGIN_AND_WORDPRESS_CORE",
  SCAN_MALWARE_WORDPRESS: "SCAN_MALWARE_WORDPRESS",
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
  LOADING: "LOADING",
};

export default constants;
